dependencies:
    - opynfinance/squeeth-monorepo@d526210
    - OpenZeppelin/openzeppelin-contracts@3.4.2-solc-0.7
    - uniswap/v3-core@1.0.0
    - uniswap/v3-periphery@1.1.1

compiler:
    solc:
        remappings:
            - "@squeeth=opynfinance/squeeth-monorepo@d526210"
            - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.2-solc-0.7"
            - "@uniswap/v3-core=uniswap/v3-core@1.0.0"
            - "@uniswap/v3-periphery=uniswap/v3-periphery@1.1.1"